---
name: Automated Testing

on: push
  # push:
  #   branches:
  #     - main
  #     - dependent_types_new_syntax
  #     - dependent_types
  # pull_request: []

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
      - name: Build
        run: ./configure && dune build && dune install
      - name: Run tests
        run: zeluc -s main examples/my_examples/refine/unit_test.zls

